version: '3'
services:
  app:
    build: ./
    image: pracujta:latest
    ports:
      - 80:80
    volumes:
      - ./backend:/app/backend
    environment:
      PORT: 80
      DATABASE_URL: postgres://postgres:password@db/pracujta
      FLASK_DEBUG: 1
      OIDC_CLIENT_ID: pracujta
      OIDC_CLIENT_SECRET: 99188acf-689e-41e2-b949-b4c50c10233d
      OIDC_REALM: pracujta-realm
      OIDC_REDIRECT_URI: http://localhost/*
      OIDC_KEYCLOAK_ROOT_URI: http://auth:8080
      OIDC_KEYCLOAK_ROOT_URI_EXTERNAL: http://localhost:8080
    depends_on:
      - db
    restart: on-failure
  db:
    image: library/postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./backend/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  auth:
    build: ./backend/keycloak
    image: pracujta-keycloak:latest
    ports:
      - 8080:8080
    volumes:
      - ./backend/keycloak/realm-export.json:/tmp/realm-export.json
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres:password@db:5432/keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    depends_on:
      - db
    restart: on-failure
