version: '3'
services:
  app:
    build: ./
    image: pracujta-api:latest
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment:
      PORT: 80
      DATABASE_URL: postgres://postgres:password@db/pracujta
    depends_on:
      - db
    restart: on-failure
  db:
    image: library/postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pracujta
