"""initial-database-schema

Revision ID: 19ec87a942ed
Revises: 63dc71cb8788
Create Date: 2021-04-10 15:22:39.388941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ec87a942ed'
down_revision = '63dc71cb8788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('profession', sa.String(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['project_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_assignment',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['project_role.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'project_id')
    )
    op.add_column('client', sa.Column('city', sa.String(), nullable=True))
    op.add_column('client', sa.Column('contact', sa.String(), nullable=True))
    op.add_column('client', sa.Column('house_number', sa.String(), nullable=True))
    op.add_column('client', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('client', sa.Column('street', sa.String(), nullable=True))
    op.add_column('client', sa.Column('tax_id', sa.String(), nullable=False))
    op.alter_column('client', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('client', 'tax_id')
    op.drop_column('client', 'street')
    op.drop_column('client', 'postal_code')
    op.drop_column('client', 'house_number')
    op.drop_column('client', 'contact')
    op.drop_column('client', 'city')
    op.drop_table('project_assignment')
    op.drop_table('project')
    op.drop_table('project_status')
    op.drop_table('project_role')
    op.drop_table('employee')
    # ### end Alembic commands ###
