"""Invoice generation

Revision ID: 207a573132cf
Revises: be4d1f475904
Create Date: 2021-07-08 01:33:36.682722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207a573132cf'
down_revision = 'be4d1f475904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('language', sa.Enum('PL', 'EN', name='language'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('billing_begin_date', sa.Date(), nullable=False),
    sa.Column('billing_end_date', sa.Date(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('invoice_query_idx', 'invoice', ['client_id', 'billing_begin_date', 'billing_end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('invoice_query_idx', table_name='invoice')
    op.drop_table('invoice')
    op.drop_table('document')
    # ### end Alembic commands ###
