"""adding teams

Revision ID: 4e69d91b3466
Revises: 68d76de3f110
Create Date: 2021-04-30 12:56:07.407308

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '4e69d91b3466'
down_revision = '68d76de3f110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    team = op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # ### Adding sample team data ###

    op.bulk_insert(team, [
        {'name': 'Kitchen Helpers',
            'description': 'Helping cooks and keeping kitchen clean',
            'archived': False, 'created_at': datetime.now()},
        {'name': 'Chef', 'description': 'Managing kitchen staff',
            'archived': False, 'created_at': datetime.now()},
        {'name': 'Cooks', 'description': 'Cooking and preparing meals',
            'archived': False, 'created_at': datetime.now()},
        {'name': 'Managment', 'description': None,
            'archived': True, 'created_at': datetime.now()}
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    # ### end Alembic commands ###
