"""Non-null constraints on names

Revision ID: 5d2727a0e7d2
Revises: 2be0d9d3ad4f
Create Date: 2021-06-09 01:02:44.932823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2727a0e7d2'
down_revision = '2be0d9d3ad4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('project', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('client', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
