"""Adding supervisors

Revision ID: 5eeca99c5ff2
Revises: d4613ba8f4c2
Create Date: 2021-06-20 06:38:58.521563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eeca99c5ff2'
down_revision = 'd4613ba8f4c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('supervisor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['supervisor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'supervisor_id')
    # ### end Alembic commands ###
