"""Client, project and task tables

Revision ID: d2fda22f67ca
Revises: 63dc71cb8788
Create Date: 2021-04-25 20:09:15.158438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2fda22f67ca'
down_revision = '63dc71cb8788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('client', sa.Column('tax_id', sa.String(), nullable=True))
    op.add_column('client', sa.Column('street_with_number', sa.String(), nullable=True))
    op.add_column('client', sa.Column('zip_code', sa.String(), nullable=True))
    op.add_column('client', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'city')
    op.drop_column('client', 'zip_code')
    op.drop_column('client', 'street_with_number')
    op.drop_column('client', 'tax_id')
    op.drop_column('client', 'created_at')
    op.drop_table('task')
    op.drop_table('project')
    # ### end Alembic commands ###
